plugins:
  dockercompute:
    executor: central_deployment_agent
    source: https://github.com/dankilman/cloudify-dockercompute-plugin/archive/master.zip
    package_name: cloudify-dockercompute-plugin
    package_version: '0.1'

node_types:
  cloudify.nodes.docker.Compute:
    derived_from: cloudify.nodes.Compute
    interfaces:
      cloudify.interfaces.lifecycle:
        start: dockercompute.dockercompute.start
        delete: dockercompute.dockercompute.delete
    properties:
      image:
        description: >
          The docker image to deploy
        default: cloudify/centos:7
      expose:
        description: >
          List of ports which should be exposed by docker
      run_command:
        description: >
          The command to run in the container to start the compute instance
        default: /sbin/init
